### PR TITLE
WP: Ascatvod

### PR DESCRIPTION
**Pull request by iteubner**
I have added a class for reading ASCAT VOD time series data and also added a test file in the pytesmo-test-data package. However, I was not sure where to put the test file and what the file naming convention is. So this still needs to be adopted.

### CODE REVIEW

**Comment by cpaulik** [comment]
I'm not sure that this even belongs in this package. The VOD is not an offical product that any user can download? If it is just TUW internal I would add the product to the rs-data-readers package.

**Comment by iteubner** [comment]
The data are not meant for internal use. We have a bachelor student who wants to read ASCAT VOD data and he has no direct access to our internal packages. I discussed this with @shahn and we came to the conclusion that it might be good to add a VOD reader to the ascat package because there may also be other students in the future who will work with ASCAT VOD data.

**Comment by cpaulik** [comment]
I disagree. Just a few lines of code are needed to read the dataset e.g.:
```
from pynetcf.time_series import GriddedNcContiguousRaggedTs
import pygeogrids.netcdf as ncgrids

path = '/home/cpa/shares/radar/Datapool_processed/WARP/datasets/ultimate_uhnari/R1B/071_vod/datasets/'
grid_filename = '/home/cpa/shares/radar/Datapool_processed/DGG/DGG_2_1/datasets/DGGv02.1_CPv02.nc'
grid = ncgrids.load_grid(filename=grid_filename, subset_flag='ind_ld')
reader = GriddedNcContiguousRaggedTs(path, grid)
data = reader.read(2459761)
```

So I would not add a special VOD reader anywhere but rather give these instructions to anybody wanting to read the dataset.

**Comment by shahn** [comment]
I am pretty sure I was accidentally tagged here, I never discussed anything related.

**Comment by iteubner** [comment]
Hi Christoph, thanks for your suggestions. I will do that.

**Comment by cpaulik** [comment]
Ok, it seems that there was some confusion. I'll close this then. Thank you anyway for making the effort of opening a PR.

**Comment by sebhahn** [comment]
No wait, I discussed it with @iteubner and the code should be here! It wasn't me who gave to comment above (I'm @sebhahn at github)

**Comment by sebhahn** [comment]
The ASCAT VOD in NetCDF format is already available on the FTP

**Comment by cpaulik** [comment]
If it is an semi-"official" product then this is a different story. But I would in anycase simplify the proposed reader to a few lines. The special grid loading and the custom read function should not be necessary.

**Comment by iteubner** [comment]
Ok, I will shorten the reader. Also, sorry about the confusion with the names. I should have taken a look at the list of TUW-GEO members first.

**Comment by cpaulik** [comment]
I've squashed the commits on your branch into one and updated the test data repository. As soon as the tests pass we can merge this.

You should make sure that your email address in your git config is correct. The author of your commits was set to iteubner@dvlp2.geo.tuwien.ac.at. I set this to your normal email address so that the commits are linked to your github profile

**Comment by iteubner** [comment]
Thanks. I didn't realize my email was not correct - I have set it now to my normal email address.

**Pull request merged**
