### PR TITLE
Ascat reader update

### PR DESCRIPTION
**Pull request by cpaulik**
- Organize ASCAT readers to fit better with bufr data that is downloadable from H-SAF and EUMETSAT
- Add readers for netCDF format from EUMETSAT

### CODE REVIEW

**Comment by cpaulik** [comment]
@sebhahn If you do not have an comments I'll merge this.

**Comment by sebhahn** [comment]
What about renaming the h_saf file to level3 or time_series? I'm not sure if we should use the project name as the file name here.

**Comment by cpaulik** [comment]
I'm actually not that happy with the level2 name since the levels are such a poorly defined concept and actually all the H-SAF data, except probably H14, is level2 data according to common defintions. I just wanted to split the reader implementation from the specific subclass for a data source.

The naming according to data source makes sense to me since this is the reference a data user probably has?

**Comment by sebhahn** [comment]
Yes you are probably right, because the file naming is anyway defined by the data source

**Pull request merged**
