### PR TITLE
Fix dtype nan irregularities in EPS/BUFR readers

### LINKED ISSUE #65: OverflowError: Python integer -128 out of bounds for uint8
On current numpy versions for Python > 3.8, lines 1329 and 1647 in `eps_native.py` raise `OverflowError: Python integer -128 out of bounds for uint8` when setting `nan_val` on `data["swath_indicator"]`, because `data["swath_indicator"]` is of dtype `np.uint8` at this point, while the `nan_val` being set on it is `int8_nan` (-128).

https://github.com/TUW-GEO/ascat/blob/e5c02d4ccc08c59ca9057bfc148a40f0a098f792/src/ascat/read_native/eps_native.py#L1322C1-L1329C34

https://github.com/TUW-GEO/ascat/blob/e5c02d4ccc08c59ca9057bfc148a40f0a098f792/src/ascat/read_native/eps_native.py#L1623-L1647

In current numpy for Python <= 3.8 this operation casts `nan_val` to `uint8` (changing its value from -128 to 128) and produces a warning, but this warning is apparently suppressed somewhere in the script when reading from eps files. This behavior is now deprecated.

If it is possible for `swath_indicator` to have any nan values before it reaches this line, this silent casting may cause some incorrect data, but I think it's not possible, so I don't think it's an issue in that sense.

### PR DESCRIPTION
**Pull request by claytharrison**
Should fix #65, but not sure if these changes are just fixing a mistake or if the current status is intentional and these changes would disrupt something else down the line?
@sebhahn

### CODE REVIEW

**Comment by claytharrison** [comment]
If I understand the code correctly, this cast happens after 

> Edit: perhaps try adding a cast [here](https://github.com/TUW-GEO/ascat/blob/master/src/ascat/read_native/eps_native.py#L820)

If I understand the code correctly, if I add this cast, it would occur after the errors mentioned in the issue. In that case I believe making both changes, as well as adding another cast [here](https://github.com/TUW-GEO/ascat/blob/e5c02d4ccc08c59ca9057bfc148a40f0a098f792/src/ascat/read_native/eps_native.py#L860) would produce the desired result?

**Comment by claytharrison** [comment]
Also this code seems strange to me:
https://github.com/TUW-GEO/ascat/blob/e5c02d4ccc08c59ca9057bfc148a40f0a098f792/src/ascat/read_native/eps_native.py#L834-L837

We specify a new name, a new dtype, and the current nan value for each generic field. Then we pop the old name from `data`, convert it to the new dtype and assign it to the new name. Then, if the current nan value is not `None`, we find all current nans in the array and set them to `float32_nan`? Shouldn't the new nan value depend on the new dtype?

**Comment by sebhahn** [comment]
you are right, can you please try if this fixes the issue?

**Comment by claytharrison** [comment]
Working on it - out of the following integer vars, which should end up as `uint8` and which should be `int8`?

`swath_indicator`

`f_kp`

`f_usable`

`flagfield_gen2`

**Comment by claytharrison** [comment]
OK, I think I deduced the answer to the last question (`f_usable` and `swath_indicator` as `int8`,  `f_kp` as `uint8`, and `flagfield_gen2` doesn't end up in final output anyway). I think I've sorted everything now assuming that's correct.

**Comment by sebhahn** [comment]
thanks!

**Pull request merged**
